name: Fibonacci Build

on:
  push:
    branches: 
      - main
      - develop 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup and run test
      if: always()
    - run: npm install
    - run: npm test
